# ${project.name} v${project.version}
# @author     ucchy
# @license    LGPLv3
# @copyright  Copyright ucchy 2014

# -------------------- 一般設定 --------------------

# Botの名前。
botName: 'ミントちゃん'

# レスポンスのフォーマット。
responceFormat: '<&e%botName&f> %responce'

# チャットに対する自動応答をするかどうか。自動応答の内容は、responces.txt で設定できます。
responceChat: true

# サーバー参加に対する自動応答をするかどうか。応答メッセージは、messages.txt で設定できます。
responceJoinServer: true

# URLを含んだチャット発言がされたときに、URL先のタイトルを取得するかどうか。
# 応答メッセージは、messages.txt で設定できます。
getURLTitle: true

# 時報を使用するかどうか。時報の内容は timesignals.txt で設定できます。
timeSignals: true

# アラームを使用するかどうか。アラームの内容は timesignals.txt で設定できます。
alermSignals: true

# 繰り返し通知を使用するかどうか。通知の内容は timesignals.txt で設定できます。
repeatSignals: true

# 発言に対して応答するまでの遅延時間(tick)。10～15ticksくらいを指定するとちょうどいいみたいです。
responceDelayTicks: 15

# -------------------- IRC連携設定 --------------------
irc:
  # IRC連携を利用するかどうか。
  enabled: false

  # IRCのチャットに対する自動応答をするかどうか。
  responceChat: true

  # IRCのチャンネル参加に対する自動応答をするかどうか。
  responceJoinServer: true

  # IRCにURLを含んだチャット発言がされたときに、URL先のタイトルを取得するかどうか。
  getURLTitle: true

  # 接続先のIRCサーバー。
  serverHostname: 'irc.friend-chat.jp'

  # 接続先のIRCサーバーのパスワード。不要なら空にしてください。
  serverPassword: ''

  # 接続先のIRCサーバーのポート番号。
  serverPort: 6665

  # 接続先のチャンネル名。設定例→  channel: '#MintChanServer'
  channel: ''

  # BOTのニックネーム。
  nickname: 'MintChan'

  # BOTのニックネームのパスワード。不要なら空にしてください。
  nickservPassword: ''

  # 接続先のIRCサーバーの文字コード。
  # 日本のIRCサーバーは、'ISO-2022-JP'(JIS) がよく使われています。
  encoding: 'ISO-2022-JP'

  # IRCサーバーから切断するときのメッセージ
  quitMessage: 'さよなら！またね！'
